---

- include: zabbix.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  
- include: mariadb.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'


  